/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from './common';

export interface IERC7786AttributesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'atomicBundle'
      | 'executionAddress'
      | 'indirectCall'
      | 'interopBundleSalt'
      | 'interopCallValue'
      | 'useFixedFee',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'atomicBundle',
    values: [BytesLike, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: 'executionAddress', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'indirectCall', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'interopBundleSalt', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'interopCallValue', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'useFixedFee', values: [boolean]): string;

  decodeFunctionResult(functionFragment: 'atomicBundle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'executionAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'indirectCall', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'interopBundleSalt', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'interopCallValue', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'useFixedFee', data: BytesLike): Result;
}

export interface IERC7786Attributes extends BaseContract {
  connect(runner?: ContractRunner | null): IERC7786Attributes;
  waitForDeployment(): Promise<this>;

  interface: IERC7786AttributesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  atomicBundle: TypedContractMethod<
    [_flowId: BytesLike, _deadline: BigNumberish, _lowNullifierIndex: BigNumberish],
    [void],
    'view'
  >;

  executionAddress: TypedContractMethod<[_executionAddress: BytesLike], [void], 'view'>;

  indirectCall: TypedContractMethod<[_indirectCallMessageValue: BigNumberish], [void], 'view'>;

  interopBundleSalt: TypedContractMethod<[_salt: BytesLike], [void], 'view'>;

  interopCallValue: TypedContractMethod<[_interopCallValue: BigNumberish], [void], 'view'>;

  useFixedFee: TypedContractMethod<[_useFixed: boolean], [void], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: 'atomicBundle',
  ): TypedContractMethod<
    [_flowId: BytesLike, _deadline: BigNumberish, _lowNullifierIndex: BigNumberish],
    [void],
    'view'
  >;
  getFunction(
    nameOrSignature: 'executionAddress',
  ): TypedContractMethod<[_executionAddress: BytesLike], [void], 'view'>;
  getFunction(
    nameOrSignature: 'indirectCall',
  ): TypedContractMethod<[_indirectCallMessageValue: BigNumberish], [void], 'view'>;
  getFunction(
    nameOrSignature: 'interopBundleSalt',
  ): TypedContractMethod<[_salt: BytesLike], [void], 'view'>;
  getFunction(
    nameOrSignature: 'interopCallValue',
  ): TypedContractMethod<[_interopCallValue: BigNumberish], [void], 'view'>;
  getFunction(
    nameOrSignature: 'useFixedFee',
  ): TypedContractMethod<[_useFixed: boolean], [void], 'view'>;

  filters: {};
}
