/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export type L2MessageStruct = {
  txNumberInBatch: BigNumberish;
  sender: AddressLike;
  data: BytesLike;
};

export type L2MessageStructOutput = [txNumberInBatch: bigint, sender: string, data: string] & {
  txNumberInBatch: bigint;
  sender: string;
  data: string;
};

export type MessageInclusionProofStruct = {
  chainId: BigNumberish;
  l1BatchNumber: BigNumberish;
  l2MessageIndex: BigNumberish;
  message: L2MessageStruct;
  proof: BytesLike[];
};

export type MessageInclusionProofStructOutput = [
  chainId: bigint,
  l1BatchNumber: bigint,
  l2MessageIndex: bigint,
  message: L2MessageStructOutput,
  proof: string[],
] & {
  chainId: bigint;
  l1BatchNumber: bigint;
  l2MessageIndex: bigint;
  message: L2MessageStructOutput;
  proof: string[];
};

export interface IL1InteropHandlerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'MESSAGE_ROOT'
      | 'acceptOwnership'
      | 'bundleStatus'
      | 'callStatus'
      | 'executeBundle'
      | 'initialize'
      | 'owner'
      | 'pause'
      | 'paused'
      | 'pendingOwner'
      | 'receiveMessage'
      | 'renounceOwnership'
      | 'transferOwnership'
      | 'unbundleBundle'
      | 'unpause'
      | 'verifyBundle',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'BundleExecuted'
      | 'BundleUnbundled'
      | 'BundleVerified'
      | 'CallProcessed'
      | 'Initialized'
      | 'OwnershipTransferStarted'
      | 'OwnershipTransferred'
      | 'Paused'
      | 'Unpaused',
  ): EventFragment;

  encodeFunctionData(functionFragment: 'MESSAGE_ROOT', values?: undefined): string;
  encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'bundleStatus', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'callStatus', values: [BytesLike, BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'executeBundle',
    values: [BytesLike, MessageInclusionProofStruct],
  ): string;
  encodeFunctionData(functionFragment: 'initialize', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
  encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
  encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'receiveMessage',
    values: [BytesLike, BytesLike, BytesLike],
  ): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: 'unbundleBundle',
    values: [BytesLike, BigNumberish[]],
  ): string;
  encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'verifyBundle',
    values: [BytesLike, MessageInclusionProofStruct],
  ): string;

  decodeFunctionResult(functionFragment: 'MESSAGE_ROOT', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'bundleStatus', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'callStatus', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'executeBundle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'receiveMessage', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'unbundleBundle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'verifyBundle', data: BytesLike): Result;
}

export namespace BundleExecutedEvent {
  export type InputTuple = [bundleHash: BytesLike];
  export type OutputTuple = [bundleHash: string];
  export interface OutputObject {
    bundleHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BundleUnbundledEvent {
  export type InputTuple = [bundleHash: BytesLike];
  export type OutputTuple = [bundleHash: string];
  export interface OutputObject {
    bundleHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BundleVerifiedEvent {
  export type InputTuple = [bundleHash: BytesLike];
  export type OutputTuple = [bundleHash: string];
  export interface OutputObject {
    bundleHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CallProcessedEvent {
  export type InputTuple = [bundleHash: BytesLike, callIndex: BigNumberish, status: BigNumberish];
  export type OutputTuple = [bundleHash: string, callIndex: bigint, status: bigint];
  export interface OutputObject {
    bundleHash: string;
    callIndex: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IL1InteropHandler extends BaseContract {
  connect(runner?: ContractRunner | null): IL1InteropHandler;
  waitForDeployment(): Promise<this>;

  interface: IL1InteropHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  MESSAGE_ROOT: TypedContractMethod<[], [string], 'view'>;

  acceptOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  bundleStatus: TypedContractMethod<[bundleHash: BytesLike], [bigint], 'view'>;

  callStatus: TypedContractMethod<
    [bundleHash: BytesLike, callIndex: BigNumberish],
    [bigint],
    'view'
  >;

  executeBundle: TypedContractMethod<
    [_bundle: BytesLike, _proof: MessageInclusionProofStruct],
    [void],
    'nonpayable'
  >;

  initialize: TypedContractMethod<[_owner: AddressLike], [void], 'nonpayable'>;

  owner: TypedContractMethod<[], [string], 'view'>;

  pause: TypedContractMethod<[], [void], 'nonpayable'>;

  paused: TypedContractMethod<[], [boolean], 'view'>;

  pendingOwner: TypedContractMethod<[], [string], 'view'>;

  receiveMessage: TypedContractMethod<
    [arg0: BytesLike, sender: BytesLike, payload: BytesLike],
    [string],
    'payable'
  >;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  unbundleBundle: TypedContractMethod<
    [_bundle: BytesLike, _providedCallStatus: BigNumberish[]],
    [void],
    'nonpayable'
  >;

  unpause: TypedContractMethod<[], [void], 'nonpayable'>;

  verifyBundle: TypedContractMethod<
    [_bundle: BytesLike, _proof: MessageInclusionProofStruct],
    [void],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'MESSAGE_ROOT'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'bundleStatus',
  ): TypedContractMethod<[bundleHash: BytesLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'callStatus',
  ): TypedContractMethod<[bundleHash: BytesLike, callIndex: BigNumberish], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'executeBundle',
  ): TypedContractMethod<
    [_bundle: BytesLike, _proof: MessageInclusionProofStruct],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'initialize',
  ): TypedContractMethod<[_owner: AddressLike], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'owner'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'pause'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'paused'): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'receiveMessage',
  ): TypedContractMethod<
    [arg0: BytesLike, sender: BytesLike, payload: BytesLike],
    [string],
    'payable'
  >;
  getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'transferOwnership',
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'unbundleBundle',
  ): TypedContractMethod<
    [_bundle: BytesLike, _providedCallStatus: BigNumberish[]],
    [void],
    'nonpayable'
  >;
  getFunction(nameOrSignature: 'unpause'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'verifyBundle',
  ): TypedContractMethod<
    [_bundle: BytesLike, _proof: MessageInclusionProofStruct],
    [void],
    'nonpayable'
  >;

  getEvent(
    key: 'BundleExecuted',
  ): TypedContractEvent<
    BundleExecutedEvent.InputTuple,
    BundleExecutedEvent.OutputTuple,
    BundleExecutedEvent.OutputObject
  >;
  getEvent(
    key: 'BundleUnbundled',
  ): TypedContractEvent<
    BundleUnbundledEvent.InputTuple,
    BundleUnbundledEvent.OutputTuple,
    BundleUnbundledEvent.OutputObject
  >;
  getEvent(
    key: 'BundleVerified',
  ): TypedContractEvent<
    BundleVerifiedEvent.InputTuple,
    BundleVerifiedEvent.OutputTuple,
    BundleVerifiedEvent.OutputObject
  >;
  getEvent(
    key: 'CallProcessed',
  ): TypedContractEvent<
    CallProcessedEvent.InputTuple,
    CallProcessedEvent.OutputTuple,
    CallProcessedEvent.OutputObject
  >;
  getEvent(
    key: 'Initialized',
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferStarted',
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred',
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'Paused',
  ): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
  getEvent(
    key: 'Unpaused',
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    'BundleExecuted(bytes32)': TypedContractEvent<
      BundleExecutedEvent.InputTuple,
      BundleExecutedEvent.OutputTuple,
      BundleExecutedEvent.OutputObject
    >;
    BundleExecuted: TypedContractEvent<
      BundleExecutedEvent.InputTuple,
      BundleExecutedEvent.OutputTuple,
      BundleExecutedEvent.OutputObject
    >;

    'BundleUnbundled(bytes32)': TypedContractEvent<
      BundleUnbundledEvent.InputTuple,
      BundleUnbundledEvent.OutputTuple,
      BundleUnbundledEvent.OutputObject
    >;
    BundleUnbundled: TypedContractEvent<
      BundleUnbundledEvent.InputTuple,
      BundleUnbundledEvent.OutputTuple,
      BundleUnbundledEvent.OutputObject
    >;

    'BundleVerified(bytes32)': TypedContractEvent<
      BundleVerifiedEvent.InputTuple,
      BundleVerifiedEvent.OutputTuple,
      BundleVerifiedEvent.OutputObject
    >;
    BundleVerified: TypedContractEvent<
      BundleVerifiedEvent.InputTuple,
      BundleVerifiedEvent.OutputTuple,
      BundleVerifiedEvent.OutputObject
    >;

    'CallProcessed(bytes32,uint256,uint8)': TypedContractEvent<
      CallProcessedEvent.InputTuple,
      CallProcessedEvent.OutputTuple,
      CallProcessedEvent.OutputObject
    >;
    CallProcessed: TypedContractEvent<
      CallProcessedEvent.InputTuple,
      CallProcessedEvent.OutputTuple,
      CallProcessedEvent.OutputObject
    >;

    'Initialized(uint8)': TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    'OwnershipTransferStarted(address,address)': TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'Paused(address)': TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    'Unpaused(address)': TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
