/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type { IInteropHandler, IInteropHandlerInterface } from '../IInteropHandler';

const _abi = [
  {
    type: 'function',
    name: 'bundleStatus',
    inputs: [
      {
        name: 'bundleHash',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint8',
        internalType: 'enum IInteropHandlerBase.BundleStatus',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'BundleExecuted',
    inputs: [
      {
        name: 'bundleHash',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BundleUnbundled',
    inputs: [
      {
        name: 'bundleHash',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BundleVerified',
    inputs: [
      {
        name: 'bundleHash',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
    ],
    anonymous: false,
  },
] as const;

export class IInteropHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IInteropHandlerInterface {
    return new Interface(_abi) as IInteropHandlerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IInteropHandler {
    return new Contract(address, _abi, runner) as unknown as IInteropHandler;
  }
}
