/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type { IL2AssetRouter, IL2AssetRouterInterface } from '../IL2AssetRouter';

const _abi = [
  {
    type: 'function',
    name: 'BRIDGE_HUB',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IBridgehub',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'L1_ASSET_ROUTER',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'assetHandlerAddress',
    inputs: [
      {
        name: 'assetId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: 'assetHandlerAddress',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'finalizeDeposit',
    inputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: '_assetId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: '_transferData',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'finalizeDepositLegacyBridge',
    inputs: [
      {
        name: '_l1Sender',
        type: 'address',
        internalType: 'address',
      },
      {
        name: '_l2Receiver',
        type: 'address',
        internalType: 'address',
      },
      {
        name: '_l1Token',
        type: 'address',
        internalType: 'address',
      },
      {
        name: '_amount',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: '_data',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'initiateIndirectCall',
    inputs: [
      {
        name: '_chainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: '_originalCaller',
        type: 'address',
        internalType: 'address',
      },
      {
        name: '_value',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: '_data',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [
      {
        name: 'interopCallStarter',
        type: 'tuple',
        internalType: 'struct InteropCallStarter',
        components: [
          {
            name: 'to',
            type: 'bytes',
            internalType: 'bytes',
          },
          {
            name: 'data',
            type: 'bytes',
            internalType: 'bytes',
          },
          {
            name: 'callAttributes',
            type: 'bytes[]',
            internalType: 'bytes[]',
          },
        ],
      },
    ],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'setAssetHandlerAddress',
    inputs: [
      {
        name: '_originChainId',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: '_assetId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: '_assetHandlerAddress',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAssetHandlerAddressThisChain',
    inputs: [
      {
        name: '_assetRegistrationData',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: '_assetHandlerAddress',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setLegacyTokenAssetHandler',
    inputs: [
      {
        name: '_assetId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'AssetDeploymentTrackerRegistered',
    inputs: [
      {
        name: 'assetId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'additionalData',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'assetDeploymentTracker',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AssetHandlerRegistered',
    inputs: [
      {
        name: 'assetId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: '_assetHandlerAddress',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BridgehubDepositBaseTokenInitiated',
    inputs: [
      {
        name: 'chainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'from',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'assetId',
        type: 'bytes32',
        indexed: false,
        internalType: 'bytes32',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BridgehubDepositInitiated',
    inputs: [
      {
        name: 'chainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'txDataHash',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'from',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'assetId',
        type: 'bytes32',
        indexed: false,
        internalType: 'bytes32',
      },
      {
        name: 'bridgeMintCalldata',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DepositFinalizedAssetRouter',
    inputs: [
      {
        name: 'chainId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'assetId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'assetData',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
    ],
    anonymous: false,
  },
] as const;

export class IL2AssetRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IL2AssetRouterInterface {
    return new Interface(_abi) as IL2AssetRouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IL2AssetRouter {
    return new Contract(address, _abi, runner) as unknown as IL2AssetRouter;
  }
}
