/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  IL2InteropCommitmentTree,
  IL2InteropCommitmentTreeInterface,
} from '../IL2InteropCommitmentTree';

const _abi = [
  {
    type: 'function',
    name: 'leafAt',
    inputs: [
      {
        name: '_index',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IMTLeaf',
        components: [
          {
            name: 'value',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'nextIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'nextValue',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'leafCount',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
] as const;

export class IL2InteropCommitmentTree__factory {
  static readonly abi = _abi;
  static createInterface(): IL2InteropCommitmentTreeInterface {
    return new Interface(_abi) as IL2InteropCommitmentTreeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IL2InteropCommitmentTree {
    return new Contract(address, _abi, runner) as unknown as IL2InteropCommitmentTree;
  }
}
