/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type { IAtomicFlowManager, IAtomicFlowManagerInterface } from '../IAtomicFlowManager';

const _abi = [
  {
    type: 'function',
    name: 'commitmentTree',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'legState',
    inputs: [
      {
        name: '_flowId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: '_bundleHash',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint8',
        internalType: 'enum LegState',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'FlowCommitted',
    inputs: [
      {
        name: 'flowId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'bundleHash',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'deadline',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
      {
        name: 'leafIndex',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FlowRefundAuthorized',
    inputs: [
      {
        name: 'flowId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'bundleHash',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FlowRefunded',
    inputs: [
      {
        name: 'flowId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'bundleHash',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
    ],
    anonymous: false,
  },
] as const;

export class IAtomicFlowManager__factory {
  static readonly abi = _abi;
  static createInterface(): IAtomicFlowManagerInterface {
    return new Interface(_abi) as IAtomicFlowManagerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAtomicFlowManager {
    return new Contract(address, _abi, runner) as unknown as IAtomicFlowManager;
  }
}
