/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type { IERC7786Attributes, IERC7786AttributesInterface } from '../IERC7786Attributes';

const _abi = [
  {
    type: 'function',
    name: 'atomicBundle',
    inputs: [
      {
        name: '_flowId',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: '_deadline',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: '_lowNullifierIndex',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'executionAddress',
    inputs: [
      {
        name: '_executionAddress',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'indirectCall',
    inputs: [
      {
        name: '_indirectCallMessageValue',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'interopBundleSalt',
    inputs: [
      {
        name: '_salt',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'interopCallValue',
    inputs: [
      {
        name: '_interopCallValue',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'useFixedFee',
    inputs: [
      {
        name: '_useFixed',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
] as const;

export class IERC7786Attributes__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7786AttributesInterface {
    return new Interface(_abi) as IERC7786AttributesInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC7786Attributes {
    return new Contract(address, _abi, runner) as unknown as IERC7786Attributes;
  }
}
