/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export interface IAtomicFlowManagerInterface extends Interface {
  getFunction(nameOrSignature: 'commitmentTree' | 'legState'): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: 'FlowCommitted' | 'FlowRefundAuthorized' | 'FlowRefunded',
  ): EventFragment;

  encodeFunctionData(functionFragment: 'commitmentTree', values?: undefined): string;
  encodeFunctionData(functionFragment: 'legState', values: [BytesLike, BytesLike]): string;

  decodeFunctionResult(functionFragment: 'commitmentTree', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'legState', data: BytesLike): Result;
}

export namespace FlowCommittedEvent {
  export type InputTuple = [
    flowId: BytesLike,
    bundleHash: BytesLike,
    deadline: BigNumberish,
    leafIndex: BigNumberish,
  ];
  export type OutputTuple = [
    flowId: string,
    bundleHash: string,
    deadline: bigint,
    leafIndex: bigint,
  ];
  export interface OutputObject {
    flowId: string;
    bundleHash: string;
    deadline: bigint;
    leafIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlowRefundAuthorizedEvent {
  export type InputTuple = [flowId: BytesLike, bundleHash: BytesLike];
  export type OutputTuple = [flowId: string, bundleHash: string];
  export interface OutputObject {
    flowId: string;
    bundleHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlowRefundedEvent {
  export type InputTuple = [flowId: BytesLike, bundleHash: BytesLike];
  export type OutputTuple = [flowId: string, bundleHash: string];
  export interface OutputObject {
    flowId: string;
    bundleHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAtomicFlowManager extends BaseContract {
  connect(runner?: ContractRunner | null): IAtomicFlowManager;
  waitForDeployment(): Promise<this>;

  interface: IAtomicFlowManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  commitmentTree: TypedContractMethod<[], [string], 'view'>;

  legState: TypedContractMethod<[_flowId: BytesLike, _bundleHash: BytesLike], [bigint], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'commitmentTree'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'legState',
  ): TypedContractMethod<[_flowId: BytesLike, _bundleHash: BytesLike], [bigint], 'view'>;

  getEvent(
    key: 'FlowCommitted',
  ): TypedContractEvent<
    FlowCommittedEvent.InputTuple,
    FlowCommittedEvent.OutputTuple,
    FlowCommittedEvent.OutputObject
  >;
  getEvent(
    key: 'FlowRefundAuthorized',
  ): TypedContractEvent<
    FlowRefundAuthorizedEvent.InputTuple,
    FlowRefundAuthorizedEvent.OutputTuple,
    FlowRefundAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: 'FlowRefunded',
  ): TypedContractEvent<
    FlowRefundedEvent.InputTuple,
    FlowRefundedEvent.OutputTuple,
    FlowRefundedEvent.OutputObject
  >;

  filters: {
    'FlowCommitted(bytes32,bytes32,uint64,uint256)': TypedContractEvent<
      FlowCommittedEvent.InputTuple,
      FlowCommittedEvent.OutputTuple,
      FlowCommittedEvent.OutputObject
    >;
    FlowCommitted: TypedContractEvent<
      FlowCommittedEvent.InputTuple,
      FlowCommittedEvent.OutputTuple,
      FlowCommittedEvent.OutputObject
    >;

    'FlowRefundAuthorized(bytes32,bytes32)': TypedContractEvent<
      FlowRefundAuthorizedEvent.InputTuple,
      FlowRefundAuthorizedEvent.OutputTuple,
      FlowRefundAuthorizedEvent.OutputObject
    >;
    FlowRefundAuthorized: TypedContractEvent<
      FlowRefundAuthorizedEvent.InputTuple,
      FlowRefundAuthorizedEvent.OutputTuple,
      FlowRefundAuthorizedEvent.OutputObject
    >;

    'FlowRefunded(bytes32,bytes32)': TypedContractEvent<
      FlowRefundedEvent.InputTuple,
      FlowRefundedEvent.OutputTuple,
      FlowRefundedEvent.OutputObject
    >;
    FlowRefunded: TypedContractEvent<
      FlowRefundedEvent.InputTuple,
      FlowRefundedEvent.OutputTuple,
      FlowRefundedEvent.OutputObject
    >;
  };
}
