/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export interface IInteropHandlerInterface extends Interface {
  getFunction(nameOrSignature: 'bundleStatus'): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: 'BundleExecuted' | 'BundleUnbundled' | 'BundleVerified',
  ): EventFragment;

  encodeFunctionData(functionFragment: 'bundleStatus', values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: 'bundleStatus', data: BytesLike): Result;
}

export namespace BundleExecutedEvent {
  export type InputTuple = [bundleHash: BytesLike];
  export type OutputTuple = [bundleHash: string];
  export interface OutputObject {
    bundleHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BundleUnbundledEvent {
  export type InputTuple = [bundleHash: BytesLike];
  export type OutputTuple = [bundleHash: string];
  export interface OutputObject {
    bundleHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BundleVerifiedEvent {
  export type InputTuple = [bundleHash: BytesLike];
  export type OutputTuple = [bundleHash: string];
  export interface OutputObject {
    bundleHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IInteropHandler extends BaseContract {
  connect(runner?: ContractRunner | null): IInteropHandler;
  waitForDeployment(): Promise<this>;

  interface: IInteropHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  bundleStatus: TypedContractMethod<[bundleHash: BytesLike], [bigint], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: 'bundleStatus',
  ): TypedContractMethod<[bundleHash: BytesLike], [bigint], 'view'>;

  getEvent(
    key: 'BundleExecuted',
  ): TypedContractEvent<
    BundleExecutedEvent.InputTuple,
    BundleExecutedEvent.OutputTuple,
    BundleExecutedEvent.OutputObject
  >;
  getEvent(
    key: 'BundleUnbundled',
  ): TypedContractEvent<
    BundleUnbundledEvent.InputTuple,
    BundleUnbundledEvent.OutputTuple,
    BundleUnbundledEvent.OutputObject
  >;
  getEvent(
    key: 'BundleVerified',
  ): TypedContractEvent<
    BundleVerifiedEvent.InputTuple,
    BundleVerifiedEvent.OutputTuple,
    BundleVerifiedEvent.OutputObject
  >;

  filters: {
    'BundleExecuted(bytes32)': TypedContractEvent<
      BundleExecutedEvent.InputTuple,
      BundleExecutedEvent.OutputTuple,
      BundleExecutedEvent.OutputObject
    >;
    BundleExecuted: TypedContractEvent<
      BundleExecutedEvent.InputTuple,
      BundleExecutedEvent.OutputTuple,
      BundleExecutedEvent.OutputObject
    >;

    'BundleUnbundled(bytes32)': TypedContractEvent<
      BundleUnbundledEvent.InputTuple,
      BundleUnbundledEvent.OutputTuple,
      BundleUnbundledEvent.OutputObject
    >;
    BundleUnbundled: TypedContractEvent<
      BundleUnbundledEvent.InputTuple,
      BundleUnbundledEvent.OutputTuple,
      BundleUnbundledEvent.OutputObject
    >;

    'BundleVerified(bytes32)': TypedContractEvent<
      BundleVerifiedEvent.InputTuple,
      BundleVerifiedEvent.OutputTuple,
      BundleVerifiedEvent.OutputObject
    >;
    BundleVerified: TypedContractEvent<
      BundleVerifiedEvent.InputTuple,
      BundleVerifiedEvent.OutputTuple,
      BundleVerifiedEvent.OutputObject
    >;
  };
}
