/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export type InteropCallStarterStruct = {
  to: BytesLike;
  data: BytesLike;
  callAttributes: BytesLike[];
};

export type InteropCallStarterStructOutput = [
  to: string,
  data: string,
  callAttributes: string[],
] & { to: string; data: string; callAttributes: string[] };

export type InteropCallStruct = {
  version: BytesLike;
  shadowAccount: boolean;
  to: AddressLike;
  from: AddressLike;
  value: BigNumberish;
  data: BytesLike;
};

export type InteropCallStructOutput = [
  version: string,
  shadowAccount: boolean,
  to: string,
  from: string,
  value: bigint,
  data: string,
] & {
  version: string;
  shadowAccount: boolean;
  to: string;
  from: string;
  value: bigint;
  data: string;
};

export type BundleAttributesStruct = {
  executionAddress: BytesLike;
  unbundlerAddress: BytesLike;
  useFixedFee: boolean;
  salt: BytesLike;
};

export type BundleAttributesStructOutput = [
  executionAddress: string,
  unbundlerAddress: string,
  useFixedFee: boolean,
  salt: string,
] & {
  executionAddress: string;
  unbundlerAddress: string;
  useFixedFee: boolean;
  salt: string;
};

export type InteropBundleStruct = {
  version: BytesLike;
  sourceChainId: BigNumberish;
  destinationChainId: BigNumberish;
  destinationBaseTokenAssetId: BytesLike;
  interopBundleSalt: BytesLike;
  calls: InteropCallStruct[];
  bundleAttributes: BundleAttributesStruct;
};

export type InteropBundleStructOutput = [
  version: string,
  sourceChainId: bigint,
  destinationChainId: bigint,
  destinationBaseTokenAssetId: string,
  interopBundleSalt: string,
  calls: InteropCallStructOutput[],
  bundleAttributes: BundleAttributesStructOutput,
] & {
  version: string;
  sourceChainId: bigint;
  destinationChainId: bigint;
  destinationBaseTokenAssetId: string;
  interopBundleSalt: string;
  calls: InteropCallStructOutput[];
  bundleAttributes: BundleAttributesStructOutput;
};

export interface IInteropCenterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'ZK_INTEROP_FEE'
      | 'interopProtocolFee'
      | 'isInteropBundleSaltUsed'
      | 'previewBundleHash'
      | 'sendBundle'
      | 'zkToken',
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: 'InteropBundleSent'): EventFragment;

  encodeFunctionData(functionFragment: 'ZK_INTEROP_FEE', values?: undefined): string;
  encodeFunctionData(functionFragment: 'interopProtocolFee', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'isInteropBundleSaltUsed',
    values: [AddressLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'previewBundleHash',
    values: [BytesLike, InteropCallStarterStruct[], BytesLike[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'sendBundle',
    values: [BytesLike, InteropCallStarterStruct[], BytesLike[]],
  ): string;
  encodeFunctionData(functionFragment: 'zkToken', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'ZK_INTEROP_FEE', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'interopProtocolFee', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isInteropBundleSaltUsed', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'previewBundleHash', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'sendBundle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'zkToken', data: BytesLike): Result;
}

export namespace InteropBundleSentEvent {
  export type InputTuple = [
    l2l1MsgHash: BytesLike,
    interopBundleHash: BytesLike,
    interopBundle: InteropBundleStruct,
  ];
  export type OutputTuple = [
    l2l1MsgHash: string,
    interopBundleHash: string,
    interopBundle: InteropBundleStructOutput,
  ];
  export interface OutputObject {
    l2l1MsgHash: string;
    interopBundleHash: string;
    interopBundle: InteropBundleStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IInteropCenter extends BaseContract {
  connect(runner?: ContractRunner | null): IInteropCenter;
  waitForDeployment(): Promise<this>;

  interface: IInteropCenterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  ZK_INTEROP_FEE: TypedContractMethod<[], [bigint], 'view'>;

  interopProtocolFee: TypedContractMethod<[], [bigint], 'view'>;

  isInteropBundleSaltUsed: TypedContractMethod<
    [user: AddressLike, salt: BytesLike],
    [boolean],
    'view'
  >;

  previewBundleHash: TypedContractMethod<
    [
      _destinationChainId: BytesLike,
      _callStarters: InteropCallStarterStruct[],
      _bundleAttributes: BytesLike[],
    ],
    [string],
    'nonpayable'
  >;

  sendBundle: TypedContractMethod<
    [
      _destinationChainId: BytesLike,
      _callStarters: InteropCallStarterStruct[],
      _bundleAttributes: BytesLike[],
    ],
    [string],
    'payable'
  >;

  zkToken: TypedContractMethod<[], [string], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'ZK_INTEROP_FEE'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'interopProtocolFee'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'isInteropBundleSaltUsed',
  ): TypedContractMethod<[user: AddressLike, salt: BytesLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'previewBundleHash',
  ): TypedContractMethod<
    [
      _destinationChainId: BytesLike,
      _callStarters: InteropCallStarterStruct[],
      _bundleAttributes: BytesLike[],
    ],
    [string],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'sendBundle',
  ): TypedContractMethod<
    [
      _destinationChainId: BytesLike,
      _callStarters: InteropCallStarterStruct[],
      _bundleAttributes: BytesLike[],
    ],
    [string],
    'payable'
  >;
  getFunction(nameOrSignature: 'zkToken'): TypedContractMethod<[], [string], 'view'>;

  getEvent(
    key: 'InteropBundleSent',
  ): TypedContractEvent<
    InteropBundleSentEvent.InputTuple,
    InteropBundleSentEvent.OutputTuple,
    InteropBundleSentEvent.OutputObject
  >;

  filters: {
    'InteropBundleSent(bytes32,bytes32,tuple)': TypedContractEvent<
      InteropBundleSentEvent.InputTuple,
      InteropBundleSentEvent.OutputTuple,
      InteropBundleSentEvent.OutputObject
    >;
    InteropBundleSent: TypedContractEvent<
      InteropBundleSentEvent.InputTuple,
      InteropBundleSentEvent.OutputTuple,
      InteropBundleSentEvent.OutputObject
    >;
  };
}
