/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from './common';

export type IMTLeafStruct = {
  value: BigNumberish;
  nextIndex: BigNumberish;
  nextValue: BigNumberish;
};

export type IMTLeafStructOutput = [value: bigint, nextIndex: bigint, nextValue: bigint] & {
  value: bigint;
  nextIndex: bigint;
  nextValue: bigint;
};

export interface IL2InteropCommitmentTreeInterface extends Interface {
  getFunction(nameOrSignature: 'leafAt' | 'leafCount'): FunctionFragment;

  encodeFunctionData(functionFragment: 'leafAt', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'leafCount', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'leafAt', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'leafCount', data: BytesLike): Result;
}

export interface IL2InteropCommitmentTree extends BaseContract {
  connect(runner?: ContractRunner | null): IL2InteropCommitmentTree;
  waitForDeployment(): Promise<this>;

  interface: IL2InteropCommitmentTreeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  leafAt: TypedContractMethod<[_index: BigNumberish], [IMTLeafStructOutput], 'view'>;

  leafCount: TypedContractMethod<[], [bigint], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: 'leafAt',
  ): TypedContractMethod<[_index: BigNumberish], [IMTLeafStructOutput], 'view'>;
  getFunction(nameOrSignature: 'leafCount'): TypedContractMethod<[], [bigint], 'view'>;

  filters: {};
}
