import { cp, mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const root = resolve(import.meta.dir, '..');
const abiDir = join(root, 'src/core/internal/abis');
const jsonDir = join(tmpdir(), 'zksync-js-typechain-abis');
const generatedTempDir = join(tmpdir(), 'zksync-js-typechain-output');
const outputDirs = [join(root, 'src/adapters/ethers/typechain'), join(root, 'typechain')];
const generatedFiles: string[] = [];

const contracts = [
  'IAtomicFlowManager',
  'IERC7786Attributes',
  'IInteropCenter',
  'IInteropHandler',
  'IL2InteropCommitmentTree',
] as const;

await rm(jsonDir, { recursive: true, force: true });
await rm(generatedTempDir, { recursive: true, force: true });
await mkdir(jsonDir, { recursive: true });

for (const contractName of contracts) {
  const file = `${contractName}.ts`;
  const module = (await import(pathToFileURL(join(abiDir, file)).href)) as {
    default?: unknown;
  };
  if (!Array.isArray(module.default)) {
    throw new Error(`${file} does not default-export an ABI array.`);
  }
  await writeFile(join(jsonDir, `${contractName}.json`), JSON.stringify(module.default));
}

const typechain = Bun.spawn(
  [
    join(root, 'node_modules/.bin/typechain'),
    '--target',
    'ethers-v6',
    '--out-dir',
    generatedTempDir,
    join(jsonDir, '*.json'),
  ],
  { cwd: root, stdout: 'inherit', stderr: 'inherit' },
);

const exitCode = await typechain.exited;
if (exitCode !== 0) process.exit(exitCode);

for (const outputDir of outputDirs) {
  await mkdir(join(outputDir, 'factories'), { recursive: true });
  for (const contractName of contracts) {
    const contractOutput = join(outputDir, `${contractName}.ts`);
    const factoryOutput = join(outputDir, 'factories', `${contractName}__factory.ts`);
    await cp(join(generatedTempDir, `${contractName}.ts`), contractOutput);
    await cp(join(generatedTempDir, 'factories', `${contractName}__factory.ts`), factoryOutput);
    generatedFiles.push(contractOutput, factoryOutput);
  }
  await writeBarrels(outputDir);
  generatedFiles.push(join(outputDir, 'index.ts'), join(outputDir, 'factories', 'index.ts'));
}

const prettier = Bun.spawn(
  [join(root, 'node_modules/.bin/prettier'), '--write', ...generatedFiles],
  { cwd: root, stdout: 'ignore', stderr: 'inherit' },
);
const prettierExitCode = await prettier.exited;
if (prettierExitCode !== 0) process.exit(prettierExitCode);

async function writeBarrels(outputDir: string): Promise<void> {
  const contractsInOutput = (await readdir(outputDir))
    .filter((file) => file.endsWith('.ts') && !['common.ts', 'index.ts'].includes(file))
    .map((file) => file.slice(0, -3))
    .sort();

  const header = [
    '/* Autogenerated file. Do not edit manually. */',
    '/* tslint:disable */',
    '/* eslint-disable */',
  ];
  const index = [
    ...header,
    ...contractsInOutput.map((name) => `export type { ${name} } from './${name}';`),
    "export * as factories from './factories';",
    ...contractsInOutput.map(
      (name) => `export { ${name}__factory } from './factories/${name}__factory';`,
    ),
    '',
  ].join('\n');
  const factories = [
    ...header,
    ...contractsInOutput.map((name) => `export { ${name}__factory } from './${name}__factory';`),
    '',
  ].join('\n');

  await writeFile(join(outputDir, 'index.ts'), index);
  await writeFile(join(outputDir, 'factories/index.ts'), factories);
}
