const IL1ContractErrorsABI = [
  {
    type: 'error',
    name: 'AccessToFallbackDenied',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'invoker', type: 'address' },
    ],
  },
  {
    type: 'error',
    name: 'AccessToFunctionDenied',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'selector', type: 'bytes4' },
      { name: 'invoker', type: 'address' },
    ],
  },
  { type: 'error', name: 'AddressAlreadySet', inputs: [{ name: 'addr', type: 'address' }] },
  { type: 'error', name: 'AddressHasNoCode', inputs: [{ name: '', type: 'address' }] },
  {
    type: 'error',
    name: 'AddressMismatch',
    inputs: [
      { name: 'expected', type: 'address' },
      { name: 'supplied', type: 'address' },
    ],
  },
  { type: 'error', name: 'AlreadyPermanentRollup', inputs: [] },
  { type: 'error', name: 'AlreadyWhitelisted', inputs: [{ name: '', type: 'address' }] },
  { type: 'error', name: 'AmountMustBeGreaterThanZero', inputs: [] },
  {
    type: 'error',
    name: 'AssetHandlerDoesNotExist',
    inputs: [{ name: 'assetId', type: 'bytes32' }],
  },
  {
    type: 'error',
    name: 'AssetHandlerNotRegistered',
    inputs: [{ name: 'assetId', type: 'bytes32' }],
  },
  { type: 'error', name: 'AssetIdAlreadyRegistered', inputs: [] },
  {
    type: 'error',
    name: 'AssetIdMismatch',
    inputs: [
      { name: 'expected', type: 'bytes32' },
      { name: 'supplied', type: 'bytes32' },
    ],
  },
  { type: 'error', name: 'AssetIdNotSupported', inputs: [{ name: 'assetId', type: 'bytes32' }] },
  { type: 'error', name: 'AssetRouterAllowanceNotZero', inputs: [] },
  { type: 'error', name: 'BaseTokenGasPriceDenominatorNotSet', inputs: [] },
  {
    type: 'error',
    name: 'BatchHashMismatch',
    inputs: [
      { name: 'expected', type: 'bytes32' },
      { name: 'actual', type: 'bytes32' },
    ],
  },
  { type: 'error', name: 'BatchNotExecuted', inputs: [{ name: 'batchNumber', type: 'uint256' }] },
  {
    type: 'error',
    name: 'BatchNumberMismatch',
    inputs: [
      { name: 'expectedBatchNumber', type: 'uint256' },
      { name: 'providedBatchNumber', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'BridgeHubAlreadyRegistered', inputs: [] },
  { type: 'error', name: 'BridgeMintNotImplemented', inputs: [] },
  { type: 'error', name: 'BurningNativeWETHNotSupported', inputs: [] },
  {
    type: 'error',
    name: 'BytecodeAlreadyPublished',
    inputs: [{ name: 'bytecodeHash', type: 'bytes32' }],
  },
  { type: 'error', name: 'CallerNotTimerAdmin', inputs: [] },
  { type: 'error', name: 'CallNotAllowed', inputs: [{ name: 'call', type: 'bytes' }] },
  { type: 'error', name: 'CanOnlyProcessOneBatch', inputs: [] },
  { type: 'error', name: 'CantExecuteUnprovenBatches', inputs: [] },
  { type: 'error', name: 'CantRevertExecutedBatch', inputs: [] },
  { type: 'error', name: 'ChainAlreadyLive', inputs: [] },
  { type: 'error', name: 'ChainIdAlreadyExists', inputs: [] },
  { type: 'error', name: 'ChainIdCantBeCurrentChain', inputs: [] },
  { type: 'error', name: 'ChainIdMismatch', inputs: [] },
  { type: 'error', name: 'ChainIdNotRegistered', inputs: [{ name: 'chainId', type: 'uint256' }] },
  { type: 'error', name: 'ChainIdTooBig', inputs: [] },
  { type: 'error', name: 'CTMAlreadyRegistered', inputs: [] },
  { type: 'error', name: 'CTMNotRegistered', inputs: [] },
  { type: 'error', name: 'DeadlineNotYetPassed', inputs: [] },
  { type: 'error', name: 'DefaultAdminTransferNotAllowed', inputs: [] },
  { type: 'error', name: 'DelegateCallFailed', inputs: [{ name: 'returnData', type: 'bytes' }] },
  { type: 'error', name: 'DenominatorIsZero', inputs: [] },
  { type: 'error', name: 'DeployFailed', inputs: [] },
  { type: 'error', name: 'DeployingBridgedTokenForNativeToken', inputs: [] },
  { type: 'error', name: 'DepositDoesNotExist', inputs: [] },
  { type: 'error', name: 'DepositExists', inputs: [] },
  { type: 'error', name: 'DiamondAlreadyFrozen', inputs: [] },
  { type: 'error', name: 'DiamondNotFrozen', inputs: [] },
  { type: 'error', name: 'EmptyAddress', inputs: [] },
  { type: 'error', name: 'EmptyAssetId', inputs: [] },
  { type: 'error', name: 'EmptyBytes32', inputs: [] },
  { type: 'error', name: 'EmptyData', inputs: [] },
  { type: 'error', name: 'EmptyDeposit', inputs: [] },
  { type: 'error', name: 'EmptyPrecommitData', inputs: [{ name: 'batchNumber', type: 'uint256' }] },
  { type: 'error', name: 'EmptyProofLength', inputs: [] },
  { type: 'error', name: 'ETHDepositNotSupported', inputs: [] },
  {
    type: 'error',
    name: 'FacetExists',
    inputs: [
      { name: 'selector', type: 'bytes4' },
      { name: '', type: 'address' },
    ],
  },
  { type: 'error', name: 'GasPerPubdataMismatch', inputs: [] },
  { type: 'error', name: 'GenesisBatchCommitmentZero', inputs: [] },
  { type: 'error', name: 'GenesisBatchHashZero', inputs: [] },
  { type: 'error', name: 'GenesisIndexStorageZero', inputs: [] },
  { type: 'error', name: 'GenesisUpgradeZero', inputs: [] },
  { type: 'error', name: 'HashedLogIsDefault', inputs: [] },
  {
    type: 'error',
    name: 'HashMismatch',
    inputs: [
      { name: 'expected', type: 'bytes32' },
      { name: 'actual', type: 'bytes32' },
    ],
  },
  {
    type: 'error',
    name: 'IncorrectBatchBounds',
    inputs: [
      { name: 'processFromExpected', type: 'uint256' },
      { name: 'processToExpected', type: 'uint256' },
      { name: 'processFromProvided', type: 'uint256' },
      { name: 'processToProvided', type: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'IncorrectBridgeHubAddress',
    inputs: [{ name: 'bridgehub', type: 'address' }],
  },
  {
    type: 'error',
    name: 'IncorrectTokenAddressFromNTV',
    inputs: [
      { name: 'assetId', type: 'bytes32' },
      { name: 'tokenAddress', type: 'address' },
    ],
  },
  { type: 'error', name: 'InsufficientChainBalance', inputs: [] },
  {
    type: 'error',
    name: 'InvalidBatchNumber',
    inputs: [
      { name: 'provided', type: 'uint256' },
      { name: 'expected', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'InvalidCaller', inputs: [{ name: '', type: 'address' }] },
  { type: 'error', name: 'InvalidDAForPermanentRollup', inputs: [] },
  { type: 'error', name: 'InvalidDelay', inputs: [] },
  {
    type: 'error',
    name: 'InvalidLogSender',
    inputs: [
      { name: 'sender', type: 'address' },
      { name: 'logKey', type: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'InvalidMessageRoot',
    inputs: [
      { name: 'expectedMessageRoot', type: 'bytes32' },
      { name: 'providedMessageRoot', type: 'bytes32' },
    ],
  },
  { type: 'error', name: 'InvalidNTVBurnData', inputs: [] },
  {
    type: 'error',
    name: 'InvalidNumberOfBlobs',
    inputs: [
      { name: 'expected', type: 'uint256' },
      { name: 'numCommitments', type: 'uint256' },
      { name: 'numHashes', type: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'InvalidPackedPrecommitmentLength',
    inputs: [{ name: 'length', type: 'uint256' }],
  },
  { type: 'error', name: 'InvalidProof', inputs: [] },
  { type: 'error', name: 'InvalidProofLengthForFinalNode', inputs: [] },
  { type: 'error', name: 'InvalidProtocolVersion', inputs: [] },
  { type: 'error', name: 'InvalidPubdataPricingMode', inputs: [] },
  { type: 'error', name: 'InvalidSelector', inputs: [{ name: 'func', type: 'bytes4' }] },
  { type: 'error', name: 'InvalidSystemLogsLength', inputs: [] },
  { type: 'error', name: 'InvalidUpgradeTxn', inputs: [{ name: '', type: 'uint8' }] },
  { type: 'error', name: 'L2TimestampTooBig', inputs: [] },
  {
    type: 'error',
    name: 'L2WithdrawalMessageWrongLength',
    inputs: [{ name: 'messageLen', type: 'uint256' }],
  },
  { type: 'error', name: 'LegacyBridgeNotSet', inputs: [] },
  { type: 'error', name: 'LegacyBridgeUsesNonNativeToken', inputs: [] },
  { type: 'error', name: 'LegacyEncodingUsedForNonL1Token', inputs: [] },
  { type: 'error', name: 'LegacyMethodForNonL1Token', inputs: [] },
  {
    type: 'error',
    name: 'LengthIsNotDivisibleBy32',
    inputs: [{ name: 'length', type: 'uint256' }],
  },
  { type: 'error', name: 'LogAlreadyProcessed', inputs: [{ name: '', type: 'uint8' }] },
  { type: 'error', name: 'MalformedBytecode', inputs: [{ name: '', type: 'uint8' }] },
  { type: 'error', name: 'MerkleIndexOrHeightMismatch', inputs: [] },
  { type: 'error', name: 'MerkleIndexOutOfBounds', inputs: [] },
  { type: 'error', name: 'MerkleNothingToProve', inputs: [] },
  { type: 'error', name: 'MerklePathEmpty', inputs: [] },
  {
    type: 'error',
    name: 'MerklePathLengthMismatch',
    inputs: [
      { name: 'pathLength', type: 'uint256' },
      { name: 'expectedLength', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'MerklePathOutOfBounds', inputs: [] },
  {
    type: 'error',
    name: 'MerkleWrongIndex',
    inputs: [
      { name: 'index', type: 'uint256' },
      { name: 'maxNodeNumber', type: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'MerkleWrongLength',
    inputs: [
      { name: 'newLeavesLength', type: 'uint256' },
      { name: 'leafNumber', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'MigrationPaused', inputs: [] },
  { type: 'error', name: 'MigrationsNotPaused', inputs: [] },
  {
    type: 'error',
    name: 'MissingSystemLogs',
    inputs: [
      { name: 'expected', type: 'uint256' },
      { name: 'actual', type: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'MsgValueMismatch',
    inputs: [
      { name: 'expectedMsgValue', type: 'uint256' },
      { name: 'providedMsgValue', type: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'MsgValueTooLow',
    inputs: [
      { name: 'required', type: 'uint256' },
      { name: 'provided', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'NewDeadlineExceedsMaxDeadline', inputs: [] },
  { type: 'error', name: 'NewDeadlineNotGreaterThanCurrent', inputs: [] },
  { type: 'error', name: 'NoCallsProvided', inputs: [] },
  { type: 'error', name: 'NoCTMForAssetId', inputs: [{ name: 'assetId', type: 'bytes32' }] },
  { type: 'error', name: 'NoFunctionsForDiamondCut', inputs: [] },
  { type: 'error', name: 'NoFundsTransferred', inputs: [] },
  { type: 'error', name: 'NoLegacySharedBridge', inputs: [] },
  { type: 'error', name: 'NonEmptyCalldata', inputs: [] },
  { type: 'error', name: 'NonEmptyMsgValue', inputs: [] },
  { type: 'error', name: 'NonIncreasingTimestamp', inputs: [] },
  { type: 'error', name: 'NonSequentialBatch', inputs: [] },
  { type: 'error', name: 'NonSequentialVersion', inputs: [] },
  { type: 'error', name: 'NotAllowed', inputs: [{ name: 'addr', type: 'address' }] },
  { type: 'error', name: 'NotARestriction', inputs: [{ name: 'addr', type: 'address' }] },
  { type: 'error', name: 'NotAZKChain', inputs: [{ name: 'addr', type: 'address' }] },
  { type: 'error', name: 'NotInitializedReentrancyGuard', inputs: [] },
  { type: 'error', name: 'NotWhitelisted', inputs: [{ name: '', type: 'address' }] },
  { type: 'error', name: 'OnlyEraSupported', inputs: [] },
  { type: 'error', name: 'OnlySelfAllowed', inputs: [] },
  { type: 'error', name: 'OperationExists', inputs: [] },
  { type: 'error', name: 'OperationMustBePending', inputs: [] },
  { type: 'error', name: 'OperationMustBeReady', inputs: [] },
  { type: 'error', name: 'OriginChainIdNotFound', inputs: [] },
  {
    type: 'error',
    name: 'PrecommitmentMismatch',
    inputs: [
      { name: 'batchNumber', type: 'uint256' },
      { name: 'expected', type: 'bytes32' },
      { name: 'found', type: 'bytes32' },
    ],
  },
  { type: 'error', name: 'PreviousOperationNotExecuted', inputs: [] },
  { type: 'error', name: 'PriorityOperationsRollingHashMismatch', inputs: [] },
  { type: 'error', name: 'PriorityTxPubdataExceedsMaxPubDataPerBatch', inputs: [] },
  {
    type: 'error',
    name: 'ProtocolIdMismatch',
    inputs: [
      { name: 'expectedProtocolVersion', type: 'uint256' },
      { name: 'providedProtocolId', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'ProtocolIdNotGreater', inputs: [] },
  {
    type: 'error',
    name: 'PubdataGreaterThanLimit',
    inputs: [
      { name: 'limit', type: 'uint256' },
      { name: 'length', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'QueueIsEmpty', inputs: [] },
  { type: 'error', name: 'Reentrancy', inputs: [] },
  {
    type: 'error',
    name: 'RemoveFunctionFacetAddressNotZero',
    inputs: [{ name: 'facet', type: 'address' }],
  },
  { type: 'error', name: 'RemoveFunctionFacetAddressZero', inputs: [] },
  { type: 'error', name: 'RemovingPermanentRestriction', inputs: [] },
  { type: 'error', name: 'ReplaceFunctionFacetAddressZero', inputs: [] },
  {
    type: 'error',
    name: 'RestrictionWasAlreadyPresent',
    inputs: [{ name: 'restriction', type: 'address' }],
  },
  {
    type: 'error',
    name: 'RestrictionWasNotPresent',
    inputs: [{ name: 'restriction', type: 'address' }],
  },
  { type: 'error', name: 'RevertedBatchNotAfterNewLastBatch', inputs: [] },
  {
    type: 'error',
    name: 'RoleAccessDenied',
    inputs: [
      { name: 'chainAddress', type: 'address' },
      { name: 'role', type: 'bytes32' },
      { name: 'account', type: 'address' },
    ],
  },
  { type: 'error', name: 'SelectorsMustAllHaveSameFreezability', inputs: [] },
  { type: 'error', name: 'SettlementLayersMustSettleOnL1', inputs: [] },
  { type: 'error', name: 'SharedBridgeNotSet', inputs: [] },
  { type: 'error', name: 'SharedBridgeValueNotSet', inputs: [{ name: '', type: 'uint8' }] },
  { type: 'error', name: 'SlotOccupied', inputs: [] },
  { type: 'error', name: 'SystemLogsSizeTooBig', inputs: [] },
  {
    type: 'error',
    name: 'TimeNotReached',
    inputs: [
      { name: 'expectedTimestamp', type: 'uint256' },
      { name: 'actualTimestamp', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'TimerAlreadyStarted', inputs: [] },
  { type: 'error', name: 'TimestampError', inputs: [] },
  { type: 'error', name: 'TokenIsLegacy', inputs: [] },
  { type: 'error', name: 'TokenNotLegacy', inputs: [] },
  { type: 'error', name: 'TokenNotSupported', inputs: [{ name: 'token', type: 'address' }] },
  { type: 'error', name: 'TokensWithFeesNotSupported', inputs: [] },
  { type: 'error', name: 'TooHighDeploymentNonce', inputs: [] },
  { type: 'error', name: 'TooManyFactoryDeps', inputs: [] },
  { type: 'error', name: 'TooMuchGas', inputs: [] },
  { type: 'error', name: 'TransactionNotAllowed', inputs: [] },
  { type: 'error', name: 'TxHashMismatch', inputs: [] },
  { type: 'error', name: 'TxnBodyGasLimitNotEnoughGas', inputs: [] },
  {
    type: 'error',
    name: 'UnallowedImplementation',
    inputs: [{ name: 'implementationHash', type: 'bytes32' }],
  },
  { type: 'error', name: 'Unauthorized', inputs: [{ name: 'caller', type: 'address' }] },
  { type: 'error', name: 'UndefinedDiamondCutAction', inputs: [] },
  { type: 'error', name: 'UnexpectedSystemLog', inputs: [{ name: 'logKey', type: 'uint256' }] },
  { type: 'error', name: 'UnknownVerifierType', inputs: [] },
  {
    type: 'error',
    name: 'UnsupportedCommitBatchEncoding',
    inputs: [{ name: 'version', type: 'uint8' }],
  },
  { type: 'error', name: 'UnsupportedEncodingVersion', inputs: [] },
  {
    type: 'error',
    name: 'UnsupportedExecuteBatchEncoding',
    inputs: [{ name: 'version', type: 'uint8' }],
  },
  {
    type: 'error',
    name: 'UnsupportedProofBatchEncoding',
    inputs: [{ name: 'version', type: 'uint8' }],
  },
  { type: 'error', name: 'UpgradeBatchNumberIsNotZero', inputs: [] },
  { type: 'error', name: 'ValidateTxnNotEnoughGas', inputs: [] },
  {
    type: 'error',
    name: 'ValueMismatch',
    inputs: [
      { name: 'expected', type: 'uint256' },
      { name: 'actual', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'VerifiedBatchesExceedsCommittedBatches', inputs: [] },
  { type: 'error', name: 'WithdrawalAlreadyFinalized', inputs: [] },
  { type: 'error', name: 'WithdrawFailed', inputs: [] },
  { type: 'error', name: 'WrappedBaseTokenAlreadyRegistered', inputs: [] },
  {
    type: 'error',
    name: 'WrongMagicValue',
    inputs: [
      { name: 'expectedMagicValue', type: 'uint256' },
      { name: 'providedMagicValue', type: 'uint256' },
    ],
  },
  { type: 'error', name: 'ZeroAddress', inputs: [] },
  { type: 'error', name: 'ZeroChainId', inputs: [] },
  { type: 'error', name: 'ZKChainLimitReached', inputs: [] },
] as const;

export default IL1ContractErrorsABI;
